# Generated by Django 4.2.1 on 2023-05-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('tag', models.CharField(max_length=255)),
                ('timezone', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Create', 'Создано'), ('Waiting', 'Ожидание отправки'), ('Send', 'Отправка'), ('Error', 'Ошибка')], default='Create', max_length=255)),
                ('start_datetime', models.DateTimeField(auto_now=True)),
                ('end_datetime', models.DateTimeField()),
                ('message_text', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_operator_code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Send', 'Отправлено'), ('Waiting', 'Ожидание'), ('Error', 'Ошибка')], max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification_service.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification_service.mailing')),
            ],
        ),
        migrations.AddField(
            model_name='mailing',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notification_service.mobile_operator_code'),
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_operator_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification_service.mobile_operator_code'),
        ),
    ]
