# Generated by Django 4.2.1 on 2023-05-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
