# Generated by Django 4.2.1 on 2023-05-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('notification_service', '0006_alter_mailing_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='scheduleID',
            field=models.ForeignKey(default="1b4fae2b60c04471afd8cac9cc70c3ca", on_delete=django.db.models.deletion.CASCADE, to='django_q.task'),
            preserve_default=False,
        ),
    ]
