# Generated by Django 4.2.1 on 2023-05-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('notification_service', '0007_mailing_scheduleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='scheduleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_q.task'),
        ),
    ]
