# Generated by Django 4.2.1 on 2023-05-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0008_alter_mailing_scheduleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='scheduleID',
        ),
        migrations.AddField(
            model_name='message',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
