version: '3.7'
services:
  web:
    build: ./testQues
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./testQues/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
